# Generated by Django 5.0.6 on 2024-07-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='admin',
        ),
    ]
