# Generated by Django 5.0.6 on 2024-07-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_conversation_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='New Conversation', max_length=255),
            preserve_default=False,
        ),
    ]
